os: linux
language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-28.0.1
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.1"
install:
  - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
  - sudo apt-get install -y nodejs
script:
  - "./android/gradlew assembleRelease -p android/"
