os: linux

services:
  - docker

before_install:
  - docker pull chickyfam/react-native-android
  - docker run chickyfam/react-native-android -c './android/gradlew assembleRelease'

script:
  - "./android/gradlew assembleRelease"
