os: linux

language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-28.0.3
    - android-28
before_install:
  - touch /home/travis/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
  - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
  - sudo apt-get install -y nodejs
install:
  - npm --version
  - npm install
script:
  - "./android/gradlew assembleRelease -p android/"
