os: linux
dist: xenial

services:
  - docker

before_install:
  - docker pull chickyfam/react-native-android
  - docker run -it -v ${TRAVIS_BUILD_DIR}:/root chickyfam/react-native-android /bin/bash -c 'pwd'

script:
  - "pwd"
  - "ls -lAF"
  - "./chickyfam/ChickyShop/android/gradlew assembleRelease"
