os: linux

services:
  - docker

before_install:
  - docker pull chickyfam/react-native-android
  - docker run chickyfam/react-native-android /bin/sh -c 'pwd'
  - docker run chickyfam/react-native-android /bin/sh -c 'ls -lAF'

script:
  - "./chickyfam/ChickyShop/android/gradlew assembleRelease"
