os: linux
dist: xenial

services:
  - docker

before_install:
  - docker pull chickyfam/react-native-android
  - docker run -v `pwd`:/root chickyfam/react-native-android

script:
  - "./chickyfam/ChickyShop/android/gradlew assembleRelease"
