os: linux
language: android

services:
  - docker

before_install:
  - docker build -t chickyfam/react-native-android
  - docker run chickyfam/react-native-android -c './android/gradlew assembleRelease'

script:
  - "./android/gradlew assembleRelease"
